//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorImpresion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://imprentadesa.ual.es/", ConfigurationName="ServiceReference1.WSMonitorImpresionSoap")]
    public interface WSMonitorImpresionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imprentadesa.ual.es/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imprentadesa.ual.es/EjecutaSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EjecutaSQL(string SQL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMonitorImpresionSoapChannel : MonitorImpresion.ServiceReference1.WSMonitorImpresionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMonitorImpresionSoapClient : System.ServiceModel.ClientBase<MonitorImpresion.ServiceReference1.WSMonitorImpresionSoap>, MonitorImpresion.ServiceReference1.WSMonitorImpresionSoap {
        
        public WSMonitorImpresionSoapClient() {
        }
        
        public WSMonitorImpresionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMonitorImpresionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMonitorImpresionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMonitorImpresionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool EjecutaSQL(string SQL) {
            return base.Channel.EjecutaSQL(SQL);
        }
    }
}
